# Generated by Django 4.0.3 on 2022-03-29 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_listing_active_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='image',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
